.PHONY: clean All

All:
	@echo "----------Building project:[ GameHet - Debug ]----------"
	@cd "GameHet" && "$(MAKE)" -f  "GameHet.mk"
clean:
	@echo "----------Cleaning project:[ GameHet - Debug ]----------"
	@cd "GameHet" && "$(MAKE)" -f  "GameHet.mk" clean
