.PHONY: clean All

All:
	@echo "----------Building project:[ VectorsFormationMethod - Debug ]----------"
	@cd "VectorsFormationMethod" && "$(MAKE)" -f  "VectorsFormationMethod.mk"
clean:
	@echo "----------Cleaning project:[ VectorsFormationMethod - Debug ]----------"
	@cd "VectorsFormationMethod" && "$(MAKE)" -f  "VectorsFormationMethod.mk" clean
