.PHONY: clean All

All:
	@echo "----------Building project:[ UsdToInrHET - Debug ]----------"
	@cd "InrTOUsd" && "$(MAKE)" -f  "UsdToInrHET.mk"
clean:
	@echo "----------Cleaning project:[ UsdToInrHET - Debug ]----------"
	@cd "InrTOUsd" && "$(MAKE)" -f  "UsdToInrHET.mk" clean
