.PHONY: clean All

All:
	@echo "----------Building project:[ section6CHALLENGE - Debug ]----------"
	@cd "section6CHALLENGE" && "$(MAKE)" -f  "section6CHALLENGE.mk"
clean:
	@echo "----------Cleaning project:[ section6CHALLENGE - Debug ]----------"
	@cd "section6CHALLENGE" && "$(MAKE)" -f  "section6CHALLENGE.mk" clean
