.PHONY: clean All

All:
	@echo "----------Building project:[ Calculator - Debug ]----------"
	@cd "Calculator" && "$(MAKE)" -f  "Calculator.mk"
clean:
	@echo "----------Cleaning project:[ Calculator - Debug ]----------"
	@cd "Calculator" && "$(MAKE)" -f  "Calculator.mk" clean
